//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainModel FMRMRCMMGProyectoIPSDomainModel
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("697f02a7-2dd1-43bd-b756-dae8f3e8cbf0")]
	public partial class FMRMRCMMGProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// FMRMRCMMGProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x697f02a7, 0x2dd1, 0x43bd, 0xb7, 0x56, 0xda, 0xe8, 0xf3, 0xe8, 0xcb, 0xf0);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public FMRMRCMMGProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(Tapiz),
				typeof(Entidad),
				typeof(Atributo),
				typeof(Relacion),
				typeof(Elemento),
				typeof(AtributoKey),
				typeof(AtributoRelacion),
				typeof(EntidadReferencesAtributo),
				typeof(EntidadReferencesRelacion1),
				typeof(TapizHasElementoes),
				typeof(EntidadReferencesAtributoKey),
				typeof(RelacionReferencesAtributoRelacion),
				typeof(FMRMRCMMGProyectoIPSDiagram),
				typeof(ConectorEntidadAtributo),
				typeof(ConectorEntidadRelacion),
				typeof(ConectorEntidadAtributoKey),
				typeof(ConectorEntidadRelacion1),
				typeof(ConectorRelacionAtributoRelacion),
				typeof(MetaforaEntidad),
				typeof(MetaforaAtributo),
				typeof(MetaforaRelacion),
				typeof(MetaforaAtributoKey),
				typeof(MetaforaAtributoRelacion),
				typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FixUpDiagram),
				typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Tapiz), "tituloPortal", Tapiz.tituloPortalDomainPropertyId, typeof(Tapiz.tituloPortalPropertyHandler)),
				new DomainMemberInfo(typeof(Tapiz), "colorTitulo", Tapiz.colorTituloDomainPropertyId, typeof(Tapiz.colorTituloPropertyHandler)),
				new DomainMemberInfo(typeof(Tapiz), "tamañoTitulo", Tapiz.tamañoTituloDomainPropertyId, typeof(Tapiz.tamañoTituloPropertyHandler)),
				new DomainMemberInfo(typeof(Tapiz), "colorFondoPortal", Tapiz.colorFondoPortalDomainPropertyId, typeof(Tapiz.colorFondoPortalPropertyHandler)),
				new DomainMemberInfo(typeof(Tapiz), "fuenteTitulo", Tapiz.fuenteTituloDomainPropertyId, typeof(Tapiz.fuenteTituloPropertyHandler)),
				new DomainMemberInfo(typeof(Tapiz), "alineacionTitulo", Tapiz.alineacionTituloDomainPropertyId, typeof(Tapiz.alineacionTituloPropertyHandler)),
				new DomainMemberInfo(typeof(Elemento), "nombre", Elemento.nombreDomainPropertyId, typeof(Elemento.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(EntidadReferencesRelacion1), "cardinalidad", EntidadReferencesRelacion1.cardinalidadDomainPropertyId, typeof(EntidadReferencesRelacion1.cardinalidadPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(EntidadReferencesAtributo), "Entidad", EntidadReferencesAtributo.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesAtributo), "Atributo", EntidadReferencesAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesRelacion1), "Entidad", EntidadReferencesRelacion1.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesRelacion1), "Relacion", EntidadReferencesRelacion1.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasElementoes), "Tapiz", TapizHasElementoes.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasElementoes), "Elemento", TapizHasElementoes.ElementoDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesAtributoKey), "Entidad", EntidadReferencesAtributoKey.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesAtributoKey), "AtributoKey", EntidadReferencesAtributoKey.AtributoKeyDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesAtributoRelacion), "Relacion", RelacionReferencesAtributoRelacion.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesAtributoRelacion), "AtributoRelacion", RelacionReferencesAtributoRelacion.AtributoRelacionDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(18);
				createElementMap.Add(typeof(Tapiz), 0);
				createElementMap.Add(typeof(Entidad), 1);
				createElementMap.Add(typeof(Atributo), 2);
				createElementMap.Add(typeof(Relacion), 3);
				createElementMap.Add(typeof(AtributoKey), 4);
				createElementMap.Add(typeof(AtributoRelacion), 5);
				createElementMap.Add(typeof(FMRMRCMMGProyectoIPSDiagram), 6);
				createElementMap.Add(typeof(ConectorEntidadAtributo), 7);
				createElementMap.Add(typeof(ConectorEntidadAtributoKey), 8);
				createElementMap.Add(typeof(ConectorEntidadRelacion1), 9);
				createElementMap.Add(typeof(ConectorRelacionAtributoRelacion), 10);
				createElementMap.Add(typeof(MetaforaEntidad), 11);
				createElementMap.Add(typeof(MetaforaAtributo), 12);
				createElementMap.Add(typeof(MetaforaRelacion), 13);
				createElementMap.Add(typeof(MetaforaAtributoKey), 14);
				createElementMap.Add(typeof(MetaforaAtributoRelacion), 15);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new Tapiz(partition, propertyAssignments);
				case 1: return new Entidad(partition, propertyAssignments);
				case 2: return new Atributo(partition, propertyAssignments);
				case 3: return new Relacion(partition, propertyAssignments);
				case 4: return new AtributoKey(partition, propertyAssignments);
				case 5: return new AtributoRelacion(partition, propertyAssignments);
				case 6: return new FMRMRCMMGProyectoIPSDiagram(partition, propertyAssignments);
				case 7: return new ConectorEntidadAtributo(partition, propertyAssignments);
				case 8: return new ConectorEntidadAtributoKey(partition, propertyAssignments);
				case 9: return new ConectorEntidadRelacion1(partition, propertyAssignments);
				case 10: return new ConectorRelacionAtributoRelacion(partition, propertyAssignments);
				case 11: return new MetaforaEntidad(partition, propertyAssignments);
				case 12: return new MetaforaAtributo(partition, propertyAssignments);
				case 13: return new MetaforaRelacion(partition, propertyAssignments);
				case 14: return new MetaforaAtributoKey(partition, propertyAssignments);
				case 15: return new MetaforaAtributoRelacion(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(5);
				createElementLinkMap.Add(typeof(EntidadReferencesAtributo), 0);
				createElementLinkMap.Add(typeof(EntidadReferencesRelacion1), 1);
				createElementLinkMap.Add(typeof(TapizHasElementoes), 2);
				createElementLinkMap.Add(typeof(EntidadReferencesAtributoKey), 3);
				createElementLinkMap.Add(typeof(RelacionReferencesAtributoRelacion), 4);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new EntidadReferencesAtributo(partition, roleAssignments, propertyAssignments);
				case 1: return new EntidadReferencesRelacion1(partition, roleAssignments, propertyAssignments);
				case 2: return new TapizHasElementoes(partition, roleAssignments, propertyAssignments);
				case 3: return new EntidadReferencesAtributoKey(partition, roleAssignments, propertyAssignments);
				case 4: return new RelacionReferencesAtributoRelacion(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (FMRMRCMMGProyectoIPSDomainModel.resourceManager == null)
				{
					FMRMRCMMGProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(FMRMRCMMGProyectoIPSDomainModel).Assembly);
				}
				return FMRMRCMMGProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return FMRMRCMMGProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return FMRMRCMMGProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (FMRMRCMMGProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new FMRMRCMMGProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					FMRMRCMMGProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return FMRMRCMMGProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (FMRMRCMMGProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new FMRMRCMMGProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					FMRMRCMMGProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return FMRMRCMMGProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class FMRMRCMMGProyectoIPSDeleteClosure : FMRMRCMMGProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public FMRMRCMMGProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class FMRMRCMMGProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public FMRMRCMMGProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasElementoes.ElementoDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class FMRMRCMMGProyectoIPSCopyClosure : FMRMRCMMGProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public FMRMRCMMGProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class FMRMRCMMGProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public FMRMRCMMGProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: Cardinalidad
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Cardinalidad
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Cardinalidad
	{
		/// <summary>
		/// ceroAuno
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Cardinalidad.ceroAuno
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Cardinalidad/ceroAuno.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		ceroAuno = 1,
		/// <summary>
		/// ceroAn
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Cardinalidad.ceroAn
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Cardinalidad/ceroAn.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		ceroAn = 0,
		/// <summary>
		/// unoAn
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Cardinalidad.unoAn
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Cardinalidad/unoAn.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		unoAn = 2,
		/// <summary>
		/// unoAuno
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Cardinalidad.unoAuno
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Cardinalidad/unoAuno.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		unoAuno = 3,
	}
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: FuentesEnum
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.FuentesEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum FuentesEnum
	{
		/// <summary>
		/// Arial
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.FuentesEnum.Arial
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.FuentesEnum/Arial.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		Arial = 0,
		/// <summary>
		/// Verdana
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.FuentesEnum.Verdana
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.FuentesEnum/Verdana.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		Verdana = 1,
		/// <summary>
		/// TimesNewRoman
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.FuentesEnum.TimesNewRoman
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.FuentesEnum/TimesNewRoman.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		TimesNewRoman = 2,
		/// <summary>
		/// Tahoma
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.FuentesEnum.Tahoma
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.FuentesEnum/Tahoma.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		Tahoma = 3,
	}
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: PosicionTituloEnum
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.PosicionTituloEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum PosicionTituloEnum
	{
		/// <summary>
		/// Izquierda
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.PosicionTituloEnum.Izquierda
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.PosicionTituloEnum/Izquierda.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		Izquierda = 0,
		/// <summary>
		/// Derecha
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.PosicionTituloEnum.Derecha
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.PosicionTituloEnum/Derecha.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		Derecha = 2,
		/// <summary>
		/// Centro
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.PosicionTituloEnum.Centro
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.PosicionTituloEnum/Centro.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		Centro = 1,
	}
}

