//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainRelationship TapizHasEntidad
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("5e41c215-c6c7-4e55-bfd4-1bda1ff839af")]
	public partial class TapizHasEntidad : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// TapizHasEntidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x5e41c215, 0xc6c7, 0x4e55, 0xbf, 0xd4, 0x1b, 0xda, 0x1f, 0xf8, 0x39, 0xaf);
	
				
		/// <summary>
		/// Constructor
		/// Creates a TapizHasEntidad link in the same Partition as the given Tapiz
		/// </summary>
		/// <param name="source">Tapiz to use as the source of the relationship.</param>
		/// <param name="target">Entidad to use as the target of the relationship.</param>
		public TapizHasEntidad(Tapiz source, Entidad target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(TapizHasEntidad.TapizDomainRoleId, source), new DslModeling::RoleAssignment(TapizHasEntidad.EntidadDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public TapizHasEntidad(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public TapizHasEntidad(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public TapizHasEntidad(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public TapizHasEntidad(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Tapiz domain role code
		
		/// <summary>
		/// Tapiz domain role Id.
		/// </summary>
		public static readonly global::System.Guid TapizDomainRoleId = new global::System.Guid(0xa0f6320e, 0x4f4a, 0x4b43, 0xa6, 0xc6, 0x46, 0x88, 0xa8, 0xde, 0xc4, 0xb2);
		
		/// <summary>
		/// DomainRole Tapiz
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad.Tapiz
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad/Tapiz.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad/Tapiz.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad/Tapiz.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("a0f6320e-4f4a-4b43-a6c6-4688a8dec4b2")]
		public virtual Tapiz Tapiz
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Tapiz)DslModeling::DomainRoleInfo.GetRolePlayer(this, TapizDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, TapizDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Tapiz of a Entidad
		/// <summary>
		/// Gets Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Tapiz GetTapiz(Entidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, EntidadDomainRoleId) as Tapiz;
		}
		
		/// <summary>
		/// Sets Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetTapiz(Entidad element, Tapiz newTapiz)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, EntidadDomainRoleId, newTapiz);
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0xf011a26d, 0x000c, 0x4b05, 0xbe, 0x83, 0x5b, 0x79, 0xc0, 0xd6, 0x29, 0xcf);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad/Entidad.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad/Entidad.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Tapiz", PropertyDisplayNameKey="UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad/Entidad.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("f011a26d-000c-4b05-be83-5b79c0d629cf")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a Tapiz
		/// <summary>
		/// Gets a list of Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetEntidad(Tapiz element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, TapizDomainRoleId);
		}
		#endregion
		#region Tapiz link accessor
		/// <summary>
		/// Get the list of TapizHasEntidad links to a Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad> GetLinksToEntidad ( global::UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz tapizInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad>(tapizInstance, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad.TapizDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the TapizHasEntidad link to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad GetLinkToTapiz (global::UPM_IPS.FMRMRCMMGProyectoIPS.Entidad entidadInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad>(entidadInstance, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad.EntidadDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Entidad not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region TapizHasEntidad instance accessors
		
		/// <summary>
		/// Get any TapizHasEntidad links between a given Tapiz and a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad> GetLinks( global::UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz source, global::UPM_IPS.FMRMRCMMGProyectoIPS.Entidad target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad>();
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad>(source, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad.TapizDomainRoleId);
			foreach ( global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad link in links )
			{
				if ( target.Equals(link.Entidad) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one TapizHasEntidad link between a given Tapizand a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad GetLink( global::UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz source, global::UPM_IPS.FMRMRCMMGProyectoIPS.Entidad target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad>(source, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad.TapizDomainRoleId);
			foreach ( global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasEntidad link in links )
			{
				if ( target.Equals(link.Entidad) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainRelationship TapizHasAtributo
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("18f8c16e-768b-4375-8153-1f3d446f70a6")]
	public partial class TapizHasAtributo : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// TapizHasAtributo domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x18f8c16e, 0x768b, 0x4375, 0x81, 0x53, 0x1f, 0x3d, 0x44, 0x6f, 0x70, 0xa6);
	
				
		/// <summary>
		/// Constructor
		/// Creates a TapizHasAtributo link in the same Partition as the given Tapiz
		/// </summary>
		/// <param name="source">Tapiz to use as the source of the relationship.</param>
		/// <param name="target">Atributo to use as the target of the relationship.</param>
		public TapizHasAtributo(Tapiz source, Atributo target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(TapizHasAtributo.TapizDomainRoleId, source), new DslModeling::RoleAssignment(TapizHasAtributo.AtributoDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public TapizHasAtributo(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public TapizHasAtributo(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public TapizHasAtributo(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public TapizHasAtributo(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Tapiz domain role code
		
		/// <summary>
		/// Tapiz domain role Id.
		/// </summary>
		public static readonly global::System.Guid TapizDomainRoleId = new global::System.Guid(0x59e21b10, 0xb584, 0x46cd, 0xa6, 0xba, 0x3e, 0x64, 0x97, 0xa7, 0x93, 0x24);
		
		/// <summary>
		/// DomainRole Tapiz
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo.Tapiz
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo/Tapiz.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo/Tapiz.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Atributo", PropertyDisplayNameKey="UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo/Tapiz.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("59e21b10-b584-46cd-a6ba-3e6497a79324")]
		public virtual Tapiz Tapiz
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Tapiz)DslModeling::DomainRoleInfo.GetRolePlayer(this, TapizDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, TapizDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Tapiz of a Atributo
		/// <summary>
		/// Gets Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Tapiz GetTapiz(Atributo element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoDomainRoleId) as Tapiz;
		}
		
		/// <summary>
		/// Sets Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetTapiz(Atributo element, Tapiz newTapiz)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoDomainRoleId, newTapiz);
		}
		#endregion
		#region Atributo domain role code
		
		/// <summary>
		/// Atributo domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoDomainRoleId = new global::System.Guid(0xffc48bc8, 0xba3d, 0x4c99, 0x9e, 0x24, 0xf8, 0x5b, 0x55, 0x89, 0x96, 0xaf);
		
		/// <summary>
		/// DomainRole Atributo
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo.Atributo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo/Atributo.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo/Atributo.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Tapiz", PropertyDisplayNameKey="UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo/Atributo.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("ffc48bc8-ba3d-4c99-9e24-f85b558996af")]
		public virtual Atributo Atributo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Atributo)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Atributo of a Tapiz
		/// <summary>
		/// Gets a list of Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Atributo> GetAtributo(Tapiz element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Atributo>, Atributo>(element, TapizDomainRoleId);
		}
		#endregion
		#region Tapiz link accessor
		/// <summary>
		/// Get the list of TapizHasAtributo links to a Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo> GetLinksToAtributo ( global::UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz tapizInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo>(tapizInstance, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo.TapizDomainRoleId);
		}
		#endregion
		#region Atributo link accessor
		/// <summary>
		/// Get the TapizHasAtributo link to a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo GetLinkToTapiz (global::UPM_IPS.FMRMRCMMGProyectoIPS.Atributo atributoInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo>(atributoInstance, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo.AtributoDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Atributo not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region TapizHasAtributo instance accessors
		
		/// <summary>
		/// Get any TapizHasAtributo links between a given Tapiz and a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo> GetLinks( global::UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz source, global::UPM_IPS.FMRMRCMMGProyectoIPS.Atributo target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo>();
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo>(source, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo.TapizDomainRoleId);
			foreach ( global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo link in links )
			{
				if ( target.Equals(link.Atributo) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one TapizHasAtributo link between a given Tapizand a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo GetLink( global::UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz source, global::UPM_IPS.FMRMRCMMGProyectoIPS.Atributo target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo>(source, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo.TapizDomainRoleId);
			foreach ( global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasAtributo link in links )
			{
				if ( target.Equals(link.Atributo) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainRelationship TapizHasRelacion
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("01c4fbee-7ffb-4940-97d0-482a3a601e38")]
	public partial class TapizHasRelacion : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// TapizHasRelacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x01c4fbee, 0x7ffb, 0x4940, 0x97, 0xd0, 0x48, 0x2a, 0x3a, 0x60, 0x1e, 0x38);
	
				
		/// <summary>
		/// Constructor
		/// Creates a TapizHasRelacion link in the same Partition as the given Tapiz
		/// </summary>
		/// <param name="source">Tapiz to use as the source of the relationship.</param>
		/// <param name="target">Relacion to use as the target of the relationship.</param>
		public TapizHasRelacion(Tapiz source, Relacion target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(TapizHasRelacion.TapizDomainRoleId, source), new DslModeling::RoleAssignment(TapizHasRelacion.RelacionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public TapizHasRelacion(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public TapizHasRelacion(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public TapizHasRelacion(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public TapizHasRelacion(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Tapiz domain role code
		
		/// <summary>
		/// Tapiz domain role Id.
		/// </summary>
		public static readonly global::System.Guid TapizDomainRoleId = new global::System.Guid(0xc1bf1103, 0x84a2, 0x479f, 0x9a, 0x24, 0xa1, 0xfc, 0xa0, 0xe3, 0x93, 0x30);
		
		/// <summary>
		/// DomainRole Tapiz
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion.Tapiz
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion/Tapiz.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion/Tapiz.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Relacion", PropertyDisplayNameKey="UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion/Tapiz.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("c1bf1103-84a2-479f-9a24-a1fca0e39330")]
		public virtual Tapiz Tapiz
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Tapiz)DslModeling::DomainRoleInfo.GetRolePlayer(this, TapizDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, TapizDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Tapiz of a Relacion
		/// <summary>
		/// Gets Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Tapiz GetTapiz(Relacion element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, RelacionDomainRoleId) as Tapiz;
		}
		
		/// <summary>
		/// Sets Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetTapiz(Relacion element, Tapiz newTapiz)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, RelacionDomainRoleId, newTapiz);
		}
		#endregion
		#region Relacion domain role code
		
		/// <summary>
		/// Relacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid RelacionDomainRoleId = new global::System.Guid(0xd9919e3d, 0x444e, 0x4cce, 0xad, 0x52, 0x5f, 0x42, 0x51, 0xe2, 0xde, 0x0f);
		
		/// <summary>
		/// DomainRole Relacion
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion.Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion/Relacion.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion/Relacion.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Tapiz", PropertyDisplayNameKey="UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion/Relacion.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("d9919e3d-444e-4cce-ad52-5f4251e2de0f")]
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Relacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, RelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, RelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Relacion of a Tapiz
		/// <summary>
		/// Gets a list of Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Relacion> GetRelacion(Tapiz element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(element, TapizDomainRoleId);
		}
		#endregion
		#region Tapiz link accessor
		/// <summary>
		/// Get the list of TapizHasRelacion links to a Tapiz.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion> GetLinksToRelacion ( global::UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz tapizInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion>(tapizInstance, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion.TapizDomainRoleId);
		}
		#endregion
		#region Relacion link accessor
		/// <summary>
		/// Get the TapizHasRelacion link to a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion GetLinkToTapiz (global::UPM_IPS.FMRMRCMMGProyectoIPS.Relacion relacionInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion>(relacionInstance, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion.RelacionDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Relacion not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region TapizHasRelacion instance accessors
		
		/// <summary>
		/// Get any TapizHasRelacion links between a given Tapiz and a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion> GetLinks( global::UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz source, global::UPM_IPS.FMRMRCMMGProyectoIPS.Relacion target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion>();
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion>(source, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion.TapizDomainRoleId);
			foreach ( global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one TapizHasRelacion link between a given Tapizand a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion GetLink( global::UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz source, global::UPM_IPS.FMRMRCMMGProyectoIPS.Relacion target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion>(source, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion.TapizDomainRoleId);
			foreach ( global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasRelacion link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainRelationship EntidadReferencesAtributo
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("e8f7629d-9907-4554-aa2d-f41c46c74c3b")]
	public partial class EntidadReferencesAtributo : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadReferencesAtributo domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xe8f7629d, 0x9907, 0x4554, 0xaa, 0x2d, 0xf4, 0x1c, 0x46, 0xc7, 0x4c, 0x3b);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadReferencesAtributo link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">Atributo to use as the target of the relationship.</param>
		public EntidadReferencesAtributo(Entidad source, Atributo target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadReferencesAtributo.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadReferencesAtributo.AtributoDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadReferencesAtributo(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadReferencesAtributo(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadReferencesAtributo(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadReferencesAtributo(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x7ff23918, 0x9cd6, 0x443e, 0x86, 0x12, 0x05, 0x24, 0x0d, 0x3d, 0x51, 0xda);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo/Entidad.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo/Entidad.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Atributo", PropertyDisplayNameKey="UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("7ff23918-9cd6-443e-8612-05240d3d51da")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a Atributo
		/// <summary>
		/// Gets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Entidad GetEntidad(Atributo element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoDomainRoleId) as Entidad;
		}
		
		/// <summary>
		/// Sets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEntidad(Atributo element, Entidad newEntidad)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoDomainRoleId, newEntidad);
		}
		#endregion
		#region Atributo domain role code
		
		/// <summary>
		/// Atributo domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoDomainRoleId = new global::System.Guid(0x925fe10c, 0x3866, 0x4d69, 0x95, 0xca, 0xcd, 0x4a, 0x0d, 0xc9, 0xd7, 0xe7);
		
		/// <summary>
		/// DomainRole Atributo
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.Atributo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo/Atributo.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo/Atributo.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo/Atributo.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("925fe10c-3866-4d69-95ca-cd4a0dc9d7e7")]
		public virtual Atributo Atributo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Atributo)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Atributo of a Entidad
		/// <summary>
		/// Gets a list of Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Atributo> GetAtributo(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Atributo>, Atributo>(element, EntidadDomainRoleId);
		}
		#endregion
		#region cardinalidadOrigen domain property code
		
		/// <summary>
		/// cardinalidadOrigen domain property Id.
		/// </summary>
		public static readonly global::System.Guid cardinalidadOrigenDomainPropertyId = new global::System.Guid(0x334b4c9a, 0x3079, 0x405f, 0xae, 0xc6, 0x16, 0x46, 0xbd, 0x90, 0xa7, 0xf5);
		
		/// <summary>
		/// Storage for cardinalidadOrigen
		/// </summary>
		private Cardinalidad cardinalidadOrigenPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of cardinalidadOrigen domain property.
		/// Description for
		/// UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.Cardinalidad Origen
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo/cardinalidadOrigen.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo/cardinalidadOrigen.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("334b4c9a-3079-405f-aec6-1646bd90a7f5")]
		public Cardinalidad cardinalidadOrigen
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return cardinalidadOrigenPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				cardinalidadOrigenPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EntidadReferencesAtributo.cardinalidadOrigen domain property.
		/// </summary>
		internal sealed partial class cardinalidadOrigenPropertyHandler : DslModeling::DomainPropertyValueHandler<EntidadReferencesAtributo, Cardinalidad>
		{
			private cardinalidadOrigenPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EntidadReferencesAtributo.cardinalidadOrigen domain property value handler.
			/// </summary>
			public static readonly cardinalidadOrigenPropertyHandler Instance = new cardinalidadOrigenPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EntidadReferencesAtributo.cardinalidadOrigen domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return cardinalidadOrigenDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed Cardinalidad GetValue(EntidadReferencesAtributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.cardinalidadOrigenPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EntidadReferencesAtributo element, Cardinalidad newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				Cardinalidad oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.cardinalidadOrigenPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region cardinalidadFin domain property code
		
		/// <summary>
		/// cardinalidadFin domain property Id.
		/// </summary>
		public static readonly global::System.Guid cardinalidadFinDomainPropertyId = new global::System.Guid(0x87b5ae37, 0x1a19, 0x4772, 0xa8, 0x7e, 0x75, 0x88, 0x4f, 0x85, 0x48, 0xfb);
		
		/// <summary>
		/// Storage for cardinalidadFin
		/// </summary>
		private Cardinalidad cardinalidadFinPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of cardinalidadFin domain property.
		/// Description for
		/// UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.Cardinalidad Fin
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo/cardinalidadFin.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo/cardinalidadFin.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("87b5ae37-1a19-4772-a87e-75884f8548fb")]
		public Cardinalidad cardinalidadFin
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return cardinalidadFinPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				cardinalidadFinPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EntidadReferencesAtributo.cardinalidadFin domain property.
		/// </summary>
		internal sealed partial class cardinalidadFinPropertyHandler : DslModeling::DomainPropertyValueHandler<EntidadReferencesAtributo, Cardinalidad>
		{
			private cardinalidadFinPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EntidadReferencesAtributo.cardinalidadFin domain property value handler.
			/// </summary>
			public static readonly cardinalidadFinPropertyHandler Instance = new cardinalidadFinPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EntidadReferencesAtributo.cardinalidadFin domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return cardinalidadFinDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed Cardinalidad GetValue(EntidadReferencesAtributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.cardinalidadFinPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EntidadReferencesAtributo element, Cardinalidad newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				Cardinalidad oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.cardinalidadFinPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadReferencesAtributo links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo> GetLinksToAtributo ( global::UPM_IPS.FMRMRCMMGProyectoIPS.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo>(entidadInstance, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.EntidadDomainRoleId);
		}
		#endregion
		#region Atributo link accessor
		/// <summary>
		/// Get the EntidadReferencesAtributo link to a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo GetLinkToEntidad (global::UPM_IPS.FMRMRCMMGProyectoIPS.Atributo atributoInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo>(atributoInstance, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.AtributoDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Atributo not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EntidadReferencesAtributo instance accessors
		
		/// <summary>
		/// Get any EntidadReferencesAtributo links between a given Entidad and a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo> GetLinks( global::UPM_IPS.FMRMRCMMGProyectoIPS.Entidad source, global::UPM_IPS.FMRMRCMMGProyectoIPS.Atributo target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo>();
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo>(source, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo link in links )
			{
				if ( target.Equals(link.Atributo) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadReferencesAtributo link between a given Entidadand a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo GetLink( global::UPM_IPS.FMRMRCMMGProyectoIPS.Entidad source, global::UPM_IPS.FMRMRCMMGProyectoIPS.Atributo target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo>(source, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo link in links )
			{
				if ( target.Equals(link.Atributo) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainRelationship EntidadReferencesRelacion
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("1c746e4a-f643-4439-ac6d-749791b5910c")]
	public partial class EntidadReferencesRelacion : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadReferencesRelacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x1c746e4a, 0xf643, 0x4439, 0xac, 0x6d, 0x74, 0x97, 0x91, 0xb5, 0x91, 0x0c);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadReferencesRelacion link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">Relacion to use as the target of the relationship.</param>
		public EntidadReferencesRelacion(Entidad source, Relacion target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadReferencesRelacion.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadReferencesRelacion.RelacionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadReferencesRelacion(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadReferencesRelacion(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadReferencesRelacion(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadReferencesRelacion(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x4f9a326e, 0x578b, 0x486e, 0x85, 0xe5, 0x42, 0x1d, 0x75, 0x82, 0xcb, 0x11);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion/Entidad.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion/Entidad.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Relacion", PropertyDisplayNameKey="UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("4f9a326e-578b-486e-85e5-421d7582cb11")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a Relacion
		/// <summary>
		/// Gets a list of Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetEntidad(Relacion element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, RelacionDomainRoleId);
		}
		#endregion
		#region Relacion domain role code
		
		/// <summary>
		/// Relacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid RelacionDomainRoleId = new global::System.Guid(0x4aca916a, 0x50ce, 0x4b5a, 0x8f, 0xac, 0x33, 0x4f, 0xf3, 0x6a, 0xcc, 0x9c);
		
		/// <summary>
		/// DomainRole Relacion
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion.Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion/Relacion.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion/Relacion.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion/Relacion.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("4aca916a-50ce-4b5a-8fac-334ff36acc9c")]
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Relacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, RelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, RelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Relacion of a Entidad
		/// <summary>
		/// Gets Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Relacion GetRelacion(Entidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, EntidadDomainRoleId) as Relacion;
		}
		
		/// <summary>
		/// Sets Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetRelacion(Entidad element, Relacion newRelacion)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, EntidadDomainRoleId, newRelacion);
		}
		#endregion
		#region cardinalidadOrigen domain property code
		
		/// <summary>
		/// cardinalidadOrigen domain property Id.
		/// </summary>
		public static readonly global::System.Guid cardinalidadOrigenDomainPropertyId = new global::System.Guid(0xda72d8fb, 0x802b, 0x4583, 0xbd, 0xea, 0xff, 0xa2, 0x2c, 0x2c, 0xbf, 0x80);
		
		/// <summary>
		/// Storage for cardinalidadOrigen
		/// </summary>
		private Cardinalidad cardinalidadOrigenPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of cardinalidadOrigen domain property.
		/// Description for
		/// UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion.Cardinalidad Origen
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion/cardinalidadOrigen.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion/cardinalidadOrigen.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("da72d8fb-802b-4583-bdea-ffa22c2cbf80")]
		public Cardinalidad cardinalidadOrigen
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return cardinalidadOrigenPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				cardinalidadOrigenPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EntidadReferencesRelacion.cardinalidadOrigen domain property.
		/// </summary>
		internal sealed partial class cardinalidadOrigenPropertyHandler : DslModeling::DomainPropertyValueHandler<EntidadReferencesRelacion, Cardinalidad>
		{
			private cardinalidadOrigenPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EntidadReferencesRelacion.cardinalidadOrigen domain property value handler.
			/// </summary>
			public static readonly cardinalidadOrigenPropertyHandler Instance = new cardinalidadOrigenPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EntidadReferencesRelacion.cardinalidadOrigen domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return cardinalidadOrigenDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed Cardinalidad GetValue(EntidadReferencesRelacion element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.cardinalidadOrigenPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EntidadReferencesRelacion element, Cardinalidad newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				Cardinalidad oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.cardinalidadOrigenPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region cardinalidadFin domain property code
		
		/// <summary>
		/// cardinalidadFin domain property Id.
		/// </summary>
		public static readonly global::System.Guid cardinalidadFinDomainPropertyId = new global::System.Guid(0x6da12f1d, 0x7316, 0x49cf, 0x82, 0xde, 0xcf, 0xdf, 0x25, 0xac, 0x17, 0x02);
		
		/// <summary>
		/// Storage for cardinalidadFin
		/// </summary>
		private Cardinalidad cardinalidadFinPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of cardinalidadFin domain property.
		/// Description for
		/// UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion.Cardinalidad Fin
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion/cardinalidadFin.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion/cardinalidadFin.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("6da12f1d-7316-49cf-82de-cfdf25ac1702")]
		public Cardinalidad cardinalidadFin
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return cardinalidadFinPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				cardinalidadFinPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EntidadReferencesRelacion.cardinalidadFin domain property.
		/// </summary>
		internal sealed partial class cardinalidadFinPropertyHandler : DslModeling::DomainPropertyValueHandler<EntidadReferencesRelacion, Cardinalidad>
		{
			private cardinalidadFinPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EntidadReferencesRelacion.cardinalidadFin domain property value handler.
			/// </summary>
			public static readonly cardinalidadFinPropertyHandler Instance = new cardinalidadFinPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EntidadReferencesRelacion.cardinalidadFin domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return cardinalidadFinDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed Cardinalidad GetValue(EntidadReferencesRelacion element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.cardinalidadFinPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EntidadReferencesRelacion element, Cardinalidad newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				Cardinalidad oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.cardinalidadFinPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the EntidadReferencesRelacion link to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion GetLinkToRelacion (global::UPM_IPS.FMRMRCMMGProyectoIPS.Entidad entidadInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion>(entidadInstance, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion.EntidadDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Entidad not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region Relacion link accessor
		/// <summary>
		/// Get the list of EntidadReferencesRelacion links to a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion> GetLinksToEntidad ( global::UPM_IPS.FMRMRCMMGProyectoIPS.Relacion relacionInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion>(relacionInstance, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion.RelacionDomainRoleId);
		}
		#endregion
		#region EntidadReferencesRelacion instance accessors
		
		/// <summary>
		/// Get any EntidadReferencesRelacion links between a given Entidad and a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion> GetLinks( global::UPM_IPS.FMRMRCMMGProyectoIPS.Entidad source, global::UPM_IPS.FMRMRCMMGProyectoIPS.Relacion target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion>();
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion>(source, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadReferencesRelacion link between a given Entidadand a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion GetLink( global::UPM_IPS.FMRMRCMMGProyectoIPS.Entidad source, global::UPM_IPS.FMRMRCMMGProyectoIPS.Relacion target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion>(source, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
