//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainClass Tapiz
	/// The root in which all other elements are embedded. Appears as a diagram.
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("bf59fb28-24c1-4461-aa40-8b34e2c4744f")]
	public partial class Tapiz : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Tapiz domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xbf59fb28, 0x24c1, 0x4461, 0xaa, 0x40, 0x8b, 0x34, 0xe2, 0xc4, 0x74, 0x4f);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Tapiz(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Tapiz(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region tituloPortal domain property code
		
		/// <summary>
		/// tituloPortal domain property Id.
		/// </summary>
		public static readonly global::System.Guid tituloPortalDomainPropertyId = new global::System.Guid(0xc98e3bd7, 0x9b15, 0x414d, 0xb8, 0x39, 0x5a, 0x05, 0xf8, 0x40, 0x8f, 0x59);
		
		/// <summary>
		/// Storage for tituloPortal
		/// </summary>
		private global::System.String tituloPortalPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of tituloPortal domain property.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz.Titulo Portal
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz/tituloPortal.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz/tituloPortal.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("c98e3bd7-9b15-414d-b839-5a05f8408f59")]
		public global::System.String tituloPortal
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tituloPortalPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				tituloPortalPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Tapiz.tituloPortal domain property.
		/// </summary>
		internal sealed partial class tituloPortalPropertyHandler : DslModeling::DomainPropertyValueHandler<Tapiz, global::System.String>
		{
			private tituloPortalPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Tapiz.tituloPortal domain property value handler.
			/// </summary>
			public static readonly tituloPortalPropertyHandler Instance = new tituloPortalPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Tapiz.tituloPortal domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return tituloPortalDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Tapiz element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tituloPortalPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Tapiz element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tituloPortalPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region colorTitulo domain property code
		
		/// <summary>
		/// colorTitulo domain property Id.
		/// </summary>
		public static readonly global::System.Guid colorTituloDomainPropertyId = new global::System.Guid(0xdf1090ae, 0x5600, 0x4c95, 0x99, 0x97, 0x98, 0xa0, 0x86, 0x69, 0x13, 0xad);
		
		/// <summary>
		/// Storage for colorTitulo
		/// </summary>
		private global::System.String colorTituloPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of colorTitulo domain property.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz.Color Titulo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz/colorTitulo.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz/colorTitulo.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("df1090ae-5600-4c95-9997-98a0866913ad")]
		public global::System.String colorTitulo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return colorTituloPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				colorTituloPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Tapiz.colorTitulo domain property.
		/// </summary>
		internal sealed partial class colorTituloPropertyHandler : DslModeling::DomainPropertyValueHandler<Tapiz, global::System.String>
		{
			private colorTituloPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Tapiz.colorTitulo domain property value handler.
			/// </summary>
			public static readonly colorTituloPropertyHandler Instance = new colorTituloPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Tapiz.colorTitulo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return colorTituloDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Tapiz element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.colorTituloPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Tapiz element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.colorTituloPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region tamañoTitulo domain property code
		
		/// <summary>
		/// tamañoTitulo domain property Id.
		/// </summary>
		public static readonly global::System.Guid tamañoTituloDomainPropertyId = new global::System.Guid(0x901981f0, 0x8e09, 0x4f52, 0x9a, 0x43, 0xef, 0xd3, 0x6d, 0x53, 0x01, 0x81);
		
		/// <summary>
		/// Storage for tamañoTitulo
		/// </summary>
		private global::System.String tamañoTituloPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of tamañoTitulo domain property.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz.Tamaño Titulo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz/tamañoTitulo.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz/tamañoTitulo.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("901981f0-8e09-4f52-9a43-efd36d530181")]
		public global::System.String tamañoTitulo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tamañoTituloPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				tamañoTituloPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Tapiz.tamañoTitulo domain property.
		/// </summary>
		internal sealed partial class tamañoTituloPropertyHandler : DslModeling::DomainPropertyValueHandler<Tapiz, global::System.String>
		{
			private tamañoTituloPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Tapiz.tamañoTitulo domain property value handler.
			/// </summary>
			public static readonly tamañoTituloPropertyHandler Instance = new tamañoTituloPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Tapiz.tamañoTitulo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return tamañoTituloDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Tapiz element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tamañoTituloPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Tapiz element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tamañoTituloPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region colorFondoPortal domain property code
		
		/// <summary>
		/// colorFondoPortal domain property Id.
		/// </summary>
		public static readonly global::System.Guid colorFondoPortalDomainPropertyId = new global::System.Guid(0xf68c2a09, 0x9e58, 0x487b, 0xa7, 0xda, 0xfb, 0x90, 0x52, 0x01, 0x6a, 0x5a);
		
		/// <summary>
		/// Storage for colorFondoPortal
		/// </summary>
		private global::System.String colorFondoPortalPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of colorFondoPortal domain property.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz.Color Fondo Portal
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz/colorFondoPortal.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz/colorFondoPortal.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("f68c2a09-9e58-487b-a7da-fb9052016a5a")]
		public global::System.String colorFondoPortal
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return colorFondoPortalPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				colorFondoPortalPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Tapiz.colorFondoPortal domain property.
		/// </summary>
		internal sealed partial class colorFondoPortalPropertyHandler : DslModeling::DomainPropertyValueHandler<Tapiz, global::System.String>
		{
			private colorFondoPortalPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Tapiz.colorFondoPortal domain property value handler.
			/// </summary>
			public static readonly colorFondoPortalPropertyHandler Instance = new colorFondoPortalPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Tapiz.colorFondoPortal domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return colorFondoPortalDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Tapiz element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.colorFondoPortalPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Tapiz element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.colorFondoPortalPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region fuenteTitulo domain property code
		
		/// <summary>
		/// fuenteTitulo domain property Id.
		/// </summary>
		public static readonly global::System.Guid fuenteTituloDomainPropertyId = new global::System.Guid(0xd3d0d60a, 0x0ab5, 0x4c3e, 0xa6, 0x19, 0xc4, 0x26, 0xd5, 0xaf, 0x94, 0xbe);
		
		/// <summary>
		/// Storage for fuenteTitulo
		/// </summary>
		private FuentesEnum fuenteTituloPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of fuenteTitulo domain property.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz.Fuente Titulo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz/fuenteTitulo.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz/fuenteTitulo.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("d3d0d60a-0ab5-4c3e-a619-c426d5af94be")]
		public FuentesEnum fuenteTitulo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return fuenteTituloPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				fuenteTituloPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Tapiz.fuenteTitulo domain property.
		/// </summary>
		internal sealed partial class fuenteTituloPropertyHandler : DslModeling::DomainPropertyValueHandler<Tapiz, FuentesEnum>
		{
			private fuenteTituloPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Tapiz.fuenteTitulo domain property value handler.
			/// </summary>
			public static readonly fuenteTituloPropertyHandler Instance = new fuenteTituloPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Tapiz.fuenteTitulo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return fuenteTituloDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed FuentesEnum GetValue(Tapiz element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.fuenteTituloPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Tapiz element, FuentesEnum newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				FuentesEnum oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.fuenteTituloPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region alineacionTitulo domain property code
		
		/// <summary>
		/// alineacionTitulo domain property Id.
		/// </summary>
		public static readonly global::System.Guid alineacionTituloDomainPropertyId = new global::System.Guid(0x5b5b1f1c, 0x8c3c, 0x448b, 0xb3, 0xdf, 0xff, 0xc3, 0x74, 0x64, 0x6f, 0x21);
		
		/// <summary>
		/// Storage for alineacionTitulo
		/// </summary>
		private PosicionTituloEnum alineacionTituloPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of alineacionTitulo domain property.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz.Alineacion Titulo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz/alineacionTitulo.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz/alineacionTitulo.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("5b5b1f1c-8c3c-448b-b3df-ffc374646f21")]
		public PosicionTituloEnum alineacionTitulo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return alineacionTituloPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				alineacionTituloPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Tapiz.alineacionTitulo domain property.
		/// </summary>
		internal sealed partial class alineacionTituloPropertyHandler : DslModeling::DomainPropertyValueHandler<Tapiz, PosicionTituloEnum>
		{
			private alineacionTituloPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Tapiz.alineacionTitulo domain property value handler.
			/// </summary>
			public static readonly alineacionTituloPropertyHandler Instance = new alineacionTituloPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Tapiz.alineacionTitulo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return alineacionTituloDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed PosicionTituloEnum GetValue(Tapiz element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.alineacionTituloPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Tapiz element, PosicionTituloEnum newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				PosicionTituloEnum oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.alineacionTituloPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Elementoes opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Elementoes.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasElementoes.Tapiz
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Elemento> Elementoes
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Elemento>, Elemento>(global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasElementoes.TapizDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.FMRMRCMMGProyectoIPS.Elemento.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::UPM_IPS.FMRMRCMMGProyectoIPS.Elemento sourceElemento1 = sourceElement as global::UPM_IPS.FMRMRCMMGProyectoIPS.Elemento;
			if (sourceElemento1 != null)
			{
				// Create link for path TapizHasElementoes.Elementoes
				this.Elementoes.Add(sourceElemento1);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::UPM_IPS.FMRMRCMMGProyectoIPS.Elemento sourceElemento1 = sourceElement as global::UPM_IPS.FMRMRCMMGProyectoIPS.Elemento;
			if (sourceElemento1 != null)
			{
				// Delete link for path TapizHasElementoes.Elementoes
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasElementoes.GetLinks((global::UPM_IPS.FMRMRCMMGProyectoIPS.Tapiz)this, sourceElemento1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasElementoes.TapizDomainRoleId, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasElementoes.ElementoDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainClass Entidad
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Entidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.Entidad.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Entidad.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("f14a95f1-18d8-4ddc-a899-463623caca02")]
	public partial class Entidad : Elemento
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Entidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xf14a95f1, 0x18d8, 0x4ddc, 0xa8, 0x99, 0x46, 0x36, 0x23, 0xca, 0xca, 0x02);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Entidad(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Entidad(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Atributo opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Atributo.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Atributo> Atributo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Atributo>, Atributo>(global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.EntidadDomainRoleId);
			}
		}
		#endregion
		#region Relacion opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Relacion.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion1.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Relacion> Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion1.EntidadDomainRoleId);
			}
		}
		#endregion
		#region AtributoKey opposite domain role accessor
		/// <summary>
		/// Gets or sets AtributoKey.
		/// Description for
		/// UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributoKey.Entidad
		/// </summary>
		public virtual AtributoKey AtributoKey
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributoKey.EntidadDomainRoleId) as AtributoKey;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributoKey.EntidadDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainClass Atributo
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Atributo
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.Atributo.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Atributo.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("995157d2-720f-4224-9529-acb6d4eac32e")]
	public partial class Atributo : Elemento
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Atributo domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x995157d2, 0x720f, 0x4224, 0x95, 0x29, 0xac, 0xb6, 0xd4, 0xea, 0xc3, 0x2e);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Atributo(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Atributo(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Entidad opposite domain role accessor
		/// <summary>
		/// Gets or sets Entidad.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.Atributo
		/// </summary>
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.AtributoDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributo.AtributoDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainClass Relacion
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Relacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.Relacion.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Relacion.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("f199dab1-e960-43df-a3b8-ad53816ee47a")]
	public partial class Relacion : Elemento
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Relacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xf199dab1, 0xe960, 0x43df, 0xa3, 0xb8, 0xad, 0x53, 0x81, 0x6e, 0xe4, 0x7a);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Relacion(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Relacion(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Entidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Entidad.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion1.Relacion
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Entidad> Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesRelacion1.RelacionDomainRoleId);
			}
		}
		#endregion
		#region AtributoRelacion opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AtributoRelacion.
		/// Description for
		/// UPM_IPS.FMRMRCMMGProyectoIPS.RelacionReferencesAtributoRelacion.Relacion
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AtributoRelacion> AtributoRelacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoRelacion>, AtributoRelacion>(global::UPM_IPS.FMRMRCMMGProyectoIPS.RelacionReferencesAtributoRelacion.RelacionDomainRoleId);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainClass Elemento
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Elemento
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.Elemento.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Elemento.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("1b205573-ffcc-488e-b12e-a842290c05ef")]
	public abstract partial class Elemento : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Elemento domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x1b205573, 0xffcc, 0x488e, 0xb1, 0x2e, 0xa8, 0x42, 0x29, 0x0c, 0x05, 0xef);
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		protected Elemento(DslModeling::Partition partition, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region nombre domain property code
		
		/// <summary>
		/// nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid nombreDomainPropertyId = new global::System.Guid(0x356ffcd9, 0xd00b, 0x496e, 0xa3, 0xcb, 0x00, 0xfb, 0x5b, 0xa0, 0x44, 0xe7);
		
		/// <summary>
		/// Storage for nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of nombre domain property.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.Elemento.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.Elemento/nombre.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.Elemento/nombre.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("356ffcd9-d00b-496e-a3cb-00fb5ba044e7")]
		public global::System.String nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				nombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Elemento.nombre domain property.
		/// </summary>
		internal sealed partial class nombrePropertyHandler : DslModeling::DomainPropertyValueHandler<Elemento, global::System.String>
		{
			private nombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Elemento.nombre domain property value handler.
			/// </summary>
			public static readonly nombrePropertyHandler Instance = new nombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Elemento.nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return nombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Elemento element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Elemento element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Tapiz opposite domain role accessor
		/// <summary>
		/// Gets or sets Tapiz.
		/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasElementoes.Elemento
		/// </summary>
		public virtual Tapiz Tapiz
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasElementoes.ElementoDomainRoleId) as Tapiz;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.FMRMRCMMGProyectoIPS.TapizHasElementoes.ElementoDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainClass AtributoKey
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.AtributoKey
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.AtributoKey.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.AtributoKey.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("8c1c5383-bfce-43be-bb1a-90df94270206")]
	public partial class AtributoKey : Elemento
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AtributoKey domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x8c1c5383, 0xbfce, 0x43be, 0xbb, 0x1a, 0x90, 0xdf, 0x94, 0x27, 0x02, 0x06);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoKey(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoKey(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Entidad opposite domain role accessor
		/// <summary>
		/// Gets or sets Entidad.
		/// Description for
		/// UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributoKey.AtributoKey
		/// </summary>
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributoKey.AtributoKeyDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.FMRMRCMMGProyectoIPS.EntidadReferencesAtributoKey.AtributoKeyDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	/// <summary>
	/// DomainClass AtributoRelacion
	/// Description for UPM_IPS.FMRMRCMMGProyectoIPS.AtributoRelacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.FMRMRCMMGProyectoIPS.AtributoRelacion.DisplayName", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.FMRMRCMMGProyectoIPS.AtributoRelacion.Description", typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel), "UPM_IPS.FMRMRCMMGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("6cc99eea-e373-4329-badc-f1be1a369ee4")]
	public partial class AtributoRelacion : Elemento
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AtributoRelacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x6cc99eea, 0xe373, 0x4329, 0xba, 0xdc, 0xf1, 0xbe, 0x1a, 0x36, 0x9e, 0xe4);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoRelacion(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoRelacion(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Relacion opposite domain role accessor
		/// <summary>
		/// Gets or sets Relacion.
		/// Description for
		/// UPM_IPS.FMRMRCMMGProyectoIPS.RelacionReferencesAtributoRelacion.AtributoRelacion
		/// </summary>
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.FMRMRCMMGProyectoIPS.RelacionReferencesAtributoRelacion.AtributoRelacionDomainRoleId) as Relacion;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.FMRMRCMMGProyectoIPS.RelacionReferencesAtributoRelacion.AtributoRelacionDomainRoleId, value);
			}
		}
		#endregion
	}
}
