//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class Tapiz
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateTapizMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.ElementosWebbed.Count == 0)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Tapiz", "", "ElementosWebbed"),
						"DSL0001", this);
			}
		} // ValidateTapizMultiplicity
	} // class Tapiz
} // UPM_IPS.FMRMRCMMGProyectoIPS

namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class Entidad
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateEntidadMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Relacion.Count == 0)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Entidad", "", "Relacion"),
						"DSL0001", this);
			}
			if (this.AtributoKey == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Entidad", "", "AtributoKey"),
						"DSL0001", this);
			}
		} // ValidateEntidadMultiplicity
	} // class Entidad
} // UPM_IPS.FMRMRCMMGProyectoIPS

namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class Atributo
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateAtributoMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Entidad == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Atributo", "", "Entidad"),
						"DSL0001", this);
			}
		} // ValidateAtributoMultiplicity
	} // class Atributo
} // UPM_IPS.FMRMRCMMGProyectoIPS

namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class Relacion
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateRelacionMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Entidad.Count == 0)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Relacion", "", "Entidad"),
						"DSL0001", this);
			}
		} // ValidateRelacionMultiplicity
	} // class Relacion
} // UPM_IPS.FMRMRCMMGProyectoIPS

namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class AtributoKey
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateAtributoKeyMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Entidad == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"AtributoKey", "", "Entidad"),
						"DSL0001", this);
			}
		} // ValidateAtributoKeyMultiplicity
	} // class AtributoKey
} // UPM_IPS.FMRMRCMMGProyectoIPS

namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class AtributoRelacion
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateAtributoRelacionMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Relacion == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"AtributoRelacion", "", "Relacion"),
						"DSL0001", this);
			}
		} // ValidateAtributoRelacionMultiplicity
	} // class AtributoRelacion
} // UPM_IPS.FMRMRCMMGProyectoIPS

namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class Portal
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidatePortalMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Paged.Count == 0)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Portal", "", "Paged"),
						"DSL0001", this);
			}
		} // ValidatePortalMultiplicity
	} // class Portal
} // UPM_IPS.FMRMRCMMGProyectoIPS

namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class Page
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidatePageMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Portal == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Page", "", "Portal"),
						"DSL0001", this);
			}
			if (this.Fielded.Count == 0)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Page", "", "Fielded"),
						"DSL0001", this);
			}
		} // ValidatePageMultiplicity
	} // class Page
} // UPM_IPS.FMRMRCMMGProyectoIPS

namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class Field
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateFieldMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Page == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						UPM_IPS.FMRMRCMMGProyectoIPS.FMRMRCMMGProyectoIPSDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Field", "", "Page"),
						"DSL0001", this);
			}
		} // ValidateFieldMultiplicity
	} // class Field
} // UPM_IPS.FMRMRCMMGProyectoIPS

	
 