//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "FMRMRCMMG_DSLProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"FMRMRCMMGProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID FMRMRCMMGProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FMRMRCMMGProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID FMRMRCMMGProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FMRMRCMMGProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewFMRMRCMMGProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FMRMRCMMGProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string FMRMRCMMGProyectoIPSPackageId = "f82e4fc8-f4fa-4b17-bb52-00e41545370e";
		
		// Editor factory identifier
		public const string FMRMRCMMGProyectoIPSEditorFactoryId = "0ec12e17-df7d-42e8-a88d-0216e8f14f09";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string FMRMRCMMGProyectoIPSModelExplorerToolWindowId = "4cd1a443-c1c0-4294-901b-b489d93f25c6";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.FMRMRCMMGProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string FMRMRCMMGProyectoIPSCommandSetId = "8f5de4f7-d8a6-400e-ac2c-a7955e0f240a";
	}
}